# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'YourAzureServiceConnection' # Add Azure service connection in your project settings
    subscriptionId: 'YourSubscriptionId'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'YourResourceGroupName'
    location: 'YourLocation'
    templateLocation: 'Linked artifact'
    csmFile: 'path/to/your/arm-template.json'
    csmParametersFile: 'path/to/your/parameters-file.json'
    deploymentMode: 'Incremental'

